spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  security:
    user:
      name: admin
      password: 1234
      roles: admin
server:
  port: 9060
